version: '3'

services:
  microservice-database:
    image: "${DATABASE_IMAGE_NAME}"
    container_name: microservice-database
    restart: always
    ports:
      - "${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}"
    networks:
      - fh
    env_file:
      - .env

networks:
  fh:
    driver: bridge
